import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const styles = StyleSheet.create({
  productSizeBox: {
    marginTop: 10,
    borderWidth: 2,
    borderColor: '#3E54AC',
    borderRadius: 10,
    backgroundColor: Colors.iconscolor,
    width: 50, // set a width that works for your layout
    height: 30, // set a height that works for your layout
    justifyContent: 'center', // vertically center the text
    alignItems: 'center', // horizontally center the text
  },
  detailsdescription: {
    marginTop: 20,
    fontSize: 15,
    fontWeight: '400',
    color: Colors.iconscolor,
  },
  detailsSize: {
    // marginTop: 20,
    fontSize: 15,
    fontWeight: 'bold',
    color: Colors.white,
  },
  buttonQuantity: {
    backgroundColor: '#fff',
    paddingHorizontal: 2,
    paddingVertical: 2,
    height: 28,
    width: 28,
    borderRadius: 5,
    borderColor: '#3E54AC',
    borderWidth: 1,
    // top: 55,
    // left: -190,
  },
  buttonTextDecrement: {
    fontSize: 12,
    fontWeight: 'bold',
    top: 2,
    left: 9,
  },
  buttonTextIncrement: {
    fontSize: 12,
    fontWeight: 'bold',
    top: 2,
    left: 9,
  },
  quantityText: {
    fontSize: 14,
    marginHorizontal: 10,
    fontWeight: 'bold',
    color: Colors.black,
    // top: 55,
    // left: -190,
  },
  input: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    flex: 1,
    marginRight: 10,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // borderWidth: 1,
    borderRadius: 5,
    // borderColor: 'gray',
    paddingHorizontal: 10,
    height: 40,
  },
  quantityButton: {
    backgroundColor: Colors.iconscolor,
    borderRadius: 5,
    padding: 5,
    height: 30,
    width: 30,
  },
  quantityButtonText: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
    marginLeft: 5,
    marginTop: -5,
  },
  container: {
    // zIndex: 0,
    backgroundColor: '#ECF2FF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    // backgroundColor: 'white',
    width: '100%',
    height: '100%',
    // height: 800,
  },
  btnfield: {
    position: 'relative',
    width: 330,
    height: 59,
    left: 26,
    top: 650,
    backgroundColor: '#3E54AC',
    borderRadius: 8,
  },
  dbtnfield: {
    position: 'absolute',
    width: 330,
    height: 59,
    left: 26,
    top: 370,
    backgroundColor: '#3E54AC',
    borderRadius: 8,
    elevation: 10,
  },
  btntext: {
    position: 'absolute',
    left: 120,
    top: 15,
    height: 29,
    width: 104,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontSize: 20,
    color: 'white',
  },
  dheader: {
    marginTop: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  detailsContainer: {
    zIndex: 1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingVertical: 20,
    paddingHorizontal: 20,
    backgroundColor: '#ECF2FF',
    // backgroundColor: '#ECF2FF',
    flex: 1,
    // marginBottom: 120,
  },
  iconContainer: {
    height: 60,
    width: 60,
    position: 'absolute',
    top: -30,
    backgroundColor: 'white',
    borderRadius: 30,
    right: 20,
    elevation: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headTxt: {
    width: 276,
    top: 265,
    left: 95,
    fontSize: 64,
    fontFamily: 'Poppins',
    fontWeight: 'bold',
    color: '#3E54AC',
  },
  headphoto: {
    position: 'absolute',
    width: 186,
    height: 173,
    left: 95,
    top: 288,
  },
  headingtext: {
    fontSize: 16,
    fontWeight: '900',
    color: '#3E54AC',
    // width: '80%',
  },
  image: {
    flex: 0.7,
    justifyContent: 'center',
  },
  startext: {
    marginTop: 10,
    color: '#3E54AC',
    fontWeight: '700',
    fontSize: 25,
  },
  title: {
    fontFamily: '800',
    fontSize: 28,
    marginBottom: 10,
    color: '#493d8a',
    textAlign: 'center',
    fontWeight: 'bold',
  },

  sizelabel: {
    width: 200,
    height: 48.66,
    left: 20,
    top: 480,
  },
  sizebutton: {
    width: 60,
    height: 40,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(62, 84, 172, 0.65)',
    borderRadius: 3,
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sizebuttontext: {
    textAlign: 'center',
  },
  description: {
    fontWeight: '300',
    color: '#62656b',
    textAlign: 'center',
    paddingHorizontal: 64,
  },
  dateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  dateText: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#3E54AC',
  },
  datePicker: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    paddingHorizontal: 9,
  },
  dateInput: {
    fontSize: 16,
  },
  categoriesslidescontainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  card: {
    marginTop: 20,
    width: 350,
    height: 100,
    margin: 10,
    marginLeft: 20,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardImage: {
    width: '100%',
    height: '110%',
  },
  cardImagetextView: {
    position: 'absolute',
    top: '90%',
    left: '55%',
    transform: [{translateX: -50}, {translateY: -50}],
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardtext: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'poppins',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 10,
    paddingLeft: 45,
    paddingRight: 20,
    marginLeft: 20,
    marginRight: 20,
    borderWidth: 1,
    borderColor: '#3E54AC',
  },
  searchInput: {
    flex: 1,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingLeft: 100,
    color: '#3E54AC',
  },
  searchIcon: {
    position: 'absolute',
    top: 12.5,
    left: 35,
    zIndex: 1,
    opacity: 0.5,
  },

  touchableText: {
    // margin:15,
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    justifyContent: 'center',
  },
  touchablebtn: {
    height: 59,
    width: 309,
    backgroundColor: '#3E54AC',
    margin: 15,
    marginTop: 20,
    borderRadius: 8,
    color: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  touchablebtnContainer: {
    justifyContent: 'center',
    marginBottom: 20,
    // alignItems:"center",
  },

  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },
});

export default styles;
