import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const Styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: Colors.main,
    height: '100%',
    width: '100%',
  },
  touchableContainer: {
    height: 90,
    width: 300,
    flexDirection: 'row',
    // backgroundColor: 'black',
    marginLeft: 40,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headertxt: {
    fontWeight: '500',
    fontSize: 20,
    color: '#FFFFFF',
    marginTop: 15,
    marginLeft: 25,
  },
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 10,
    padding: 20,
    margin: 10,
    height: 150,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 10,
    color: Colors.white,
    marginLeft: '35%',
  },
  renteditems1: {
    fontSize: 14,
    marginLeft: '8%',
    fontWeight: '600',
    color: Colors.white,
  },
  rentalitemscard: {
    flexDirection: 'row',
    marginLeft: -15,
  },
  renteditems2: {
    fontSize: 14,
    marginLeft: '35%',
    color: Colors.white,
    fontWeight: '600',
  },
  cardsrentalprices: {
    fontSize: 14,
    marginLeft: '17%',
    color: Colors.white,
    fontWeight: '600',
    marginTop: 10,
  },
  cardsTotalprices: {
    fontSize: 14,
    fontWeight: '600',
    marginLeft: '57%',
    color: Colors.white,
    marginTop: 10,
  },
  recentlyaddedcontainer: {
    height: 150,
    width: '100%',
    backgroundColor: 'white',
    marginBottom: 10,
  },
  recentlyaddedcard: {
    // backgroundColor: Colors.black,
    borderRadius: 10,
    // padding: 20,
    margin: 5,
    marginLeft: 15,
    marginRight: 10,
    width: 155,
    // width: '40%',
    // marginTop: 10,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: -15,
  },
  recentlyaddedimage: {
    width: '159%',
    height: 150,
    alignSelf: 'center',
    marginBottom: 10,
    borderRadius: 8,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: Colors.Inputtext,
  },
  recentlyaddedname: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: Colors.iconscolor,
  },
  cardText: {
    color: '#FFFFFF',
    textAlign: 'left',
    fontWeight: '500',
    fontFamily: 'Poppins',
    height: 20,
    width: '100%',
    marginTop: 5,
    marginLeft: 10,
  },
  cardTextPrice: {
    color: '#9747FF',
    textAlign: 'left',
    fontFamily: 'Poppins',
    marginLeft: 10,
    marginTop: 5,
    fontSize: 14,
    fontWeight: '700',
  },
  cardContainer: {
    width: '67%',
    height: 150,
    alignSelf: 'center',
  },
  cardTextContainer: {
    width: '107%',
    height: 55,
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 8,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  recentlyaddedprice: {
    fontSize: 16,
    textAlign: 'center',
  },
  Rentalhistory: {
    fontWeight: 'bold',
    fontSize: 20,
    backgroundColor: '#000000',
    color: Colors.iconscolor,
    marginLeft: 25,
  },
});
export default Styles;
