import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const Styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: Colors.main,
    height: '100%',
    width: '100%',
  },
  touchableContainer: {
    height: 90,
    width: 300,
    flexDirection: 'row',
    // backgroundColor: 'black',
    marginLeft: 40,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headertxt: {
    fontWeight: '500',
    fontSize: 20,
    color: 'black',
    marginTop: 15,
    marginLeft: 20,
  },
  Viewmore: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    height: 20,
    width: '30%',
    marginLeft: '36%',
    marginTop: -19,
    borderRadius: 20,
    flexDirection: 'row',
  },
  exportContainer: {
    width: '30%',
    height: 40,
    backgroundColor: Colors.buttonColor,
    borderRadius: 15,
    justifyContent: 'center',
    marginLeft: '65%',
    alignItems: 'center',
    flexDirection: 'row',
  },
  exportText: {
    color: Colors.white,
    fontFamily: 'Poppins-Medium',

    size: 14,
  },
  card: {
    backgroundColor: Colors.buttonColor,
    borderRadius: 10,
    padding: 20,
    margin: 10,
    height: 150,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 10,
    color: Colors.white,
    marginLeft: '35%',
  },
  renteditems1: {
    fontSize: 14,
    marginLeft: '8%',
    fontWeight: '600',
    color: Colors.white,
  },
  rentalitemscard: {
    flexDirection: 'row',
    marginLeft: -15,
  },
  renteditems2: {
    fontSize: 14,
    marginLeft: '35%',
    color: Colors.white,
    fontWeight: '600',
  },
  cardsrentalprices: {
    fontSize: 14,
    marginLeft: '12%',
    // marginTop: 7,
  },
  cardsTotalprices: {
    marginLeft: '44%',
    // marginTop: 10,
  },
  recentlyaddedcontainer: {
    height: 150,
    width: '100%',
    backgroundColor: 'white',
    marginBottom: 10,
  },
  recentlyaddedcard: {
    // backgroundColor: Colors.black,
    borderRadius: 10,
    // padding: 20,
    margin: 5,
    marginLeft: 15,
    marginRight: 10,
    width: 155,
    // width: '40%',
    // marginTop: 10,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: -15,
  },
  recentlyaddedimage: {
    width: '159%',
    height: 150,
    alignSelf: 'center',
    marginBottom: 10,
    borderRadius: 8,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: Colors.Inputtext,
  },
  recentlyaddedname: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: Colors.iconscolor,
  },
  cardText: {
    color: 'black',
    textAlign: 'left',
    fontWeight: '500',
    fontFamily: 'Poppins',
    height: 20,
    width: '100%',
    marginTop: 5,
    marginLeft: 10,
  },
  cardTextPrice: {
    color: '#9747FF',
    textAlign: 'left',
    fontFamily: 'Poppins',
    marginLeft: 10,
    marginTop: 5,
    fontSize: 14,
    fontWeight: '700',
  },
  cardContainer: {
    width: '67%',
    height: 150,
    backgroundColor: 'white',
    alignSelf: 'center',
  },
  cardTextContainer: {
    width: '107%',
    height: 55,
    alignSelf: 'center',
    backgroundColor: 'white',
    borderRadius: 8,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  recentlyaddedprice: {
    fontSize: 16,
    textAlign: 'center',
  },
  Rentalhistory: {
    fontWeight: 'bold',
    fontSize: 20,
    backgroundColor: '#000000',
    color: Colors.iconscolor,
    marginLeft: 25,
  },
  dashcardContainer: {
    width: '50%',
    height: 150,
    // alignSelf: 'center',
    flexDirection: 'row',
  },
  dashcard: {
    backgroundColor: Colors.buttonColor,
    borderRadius: 10,
    padding: 10,
    width: '85%',
    flexDirection: 'row',
    margin: 28,
    height: 120,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 4,
  },
  Order: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.white,
    marginLeft: '30%',
  },
  Product: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.white,
    marginLeft: '30%',
    width: '80%',
  },
  price: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.white,
    marginLeft: '30%',
  },
  order: {
    fontFamily: 'Poppins-SemiBold',
    color: Colors.white,
    marginLeft: '30%',
  },
  dashboardimage: {
    width: '60%',
    height: 100,
    borderRadius: 8,
  },
});
export default Styles;
