import {StyleSheet} from 'react-native';
const style = StyleSheet.create({
  btnfield: {
    alignItems: 'center',
    flexDirection: 'row',
    width: 300,
    height: 59,
    marginTop: 30,
    marginLeft: 45,
    backgroundColor: '#3E54AC',
    borderRadius: 13,
  },
  btntext: {
    position: 'absolute',
    left: 125,
    top: 15,
    height: 29,
    width: 104,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontSize: 20,
    color: 'white',
  },
  profileImg: {
    height: 100,
    width: 100,
    borderRadius: 50,
    borderColor: 'red',
    shadowColor: '#3E54AC',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3,
    marginTop: 80,
  },
  imageContainer: {
    // marginTop: 50,
    zIndex: 1,
  },
  profileStyle: {
    width: '100%',
    height: '100%',
    backgroundColor: '#ECF2FF',
    zIndex: 1,
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  profileText: {
    textAlign: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    color: '#3E54AC',
    fontFamily: 'poppins',
    fontSize: 22,
    padding: 16,
  },
  profileFields: {
    height: 300,
    marginLeft: 45,
  },
  editprofile: {
    backgroundColor: '#FFFFFF',
    color: 'white',
  },
  whiteBtn: {
    alignItems: 'center',
    textAlign: 'center',
    width: 300,
    height: 59,
    backgroundColor: 'white',
    flexDirection: 'row',
    borderRadius: 13,
    marginBottom: 15,
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  btnPText: {
    position: 'absolute',
    left: 100,
    top: 15,
    height: 29,
    width: 200,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontSize: 19,
    color: '#3E54AC',
    alignItems: 'center',
  },
  AddressbtnPText: {
    position: 'absolute',
    left: 110,
    top: 15,
    height: 29,
    width: 200,
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontSize: 20,
    color: '#3E54AC',
    alignItems: 'center',
  },
  //switch button css
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  icon: {
    backgroundColor: '#3E54AC',
    borderRadius: 50,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  text: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  label: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  buttonContainer: {
    // position: 'absolute',
    // top: 0,
    // right: 0,
    // margin: 20,
    marginTop: 15,
    zIndex: 2,
  },
});
export default style;
