import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const OwnerEditItemstyles = StyleSheet.create({
  buttenContainer: {
    flexDirection: 'column',
    height: 200,
    width: 145,
    justifyContent: 'center',
    // alignItems: 'center',
    // flexDirection: 'column',
    // alignItems: 'center',
    // justifyContent: 'center',
    // marginVertical: 10,
  },
  card: {
    height: 180,
    width: 160,
    borderRadius: 10,
    // opacity: 0.5,
    flexDirection: 'column',
    // backgroundColor: '#D2E5F1',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    marginRight: 20,
    marginLeft: 20,
    marginTop: 40,
    // backgroundColor: Colors.black,
    // borderRadius: 10,
    // // shadowColor: Colors.shadow,
    // shadowOffset: {width: 0, height: 3},
    // shadowOpacity: 0.5,
    // shadowRadius: 5,
    // elevation: 5,
    // width: 160,
    // height: 150,
    // margin: 5,
    // alignItems: 'center'
  },
  Container: {
    // alignSelf:'flex-end',
    // flexDirection: 'column',
    // alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    width: '100%',
    marginRight: 10,
    marginLeft: 10,
    // marginBottom: 50,
  },
  imageContainer: {
    height: 150,
    width: 145,
    borderRadius: 10,
    opacity: 2,
    justifyContent: 'center',
    backgroundColor: '#000',
  },
  text: {
    color: '#3E54AC',
    fontWeight: 'bold',
    flexDirection: 'column',
    marginLeft: 8,
    marginTop: 8,
    marginRight: 8,
    marginBottom: 5,
    // marginRight: 10,
  },
  mainContainer: {
    backgroundColor: Colors.main,
    height: '100%',
    width: '100%',
    alignItems: 'center',
  },
  Titletext: {
    fontSize: 18,
    fontWeight: '900',
    color: Colors.iconscolor,
    marginLeft: 20,
    marginTop: 10,
  },
  TotalContainer: {
    justifyContent: 'space-between',
    padding: 20,
    flexDirection: 'column',
  },
  textContainer: {
    flexDirection: 'column',
    backgroundColor: '#3E54AC1A',
    marginTop: 10,
    width: 145,
    borderRadius: 10,
  },
  cardImage: {
    height: 145,
    width: 145,
    borderRadius: 8,
  },
  cardImageContainer: {
    // backgroundColor: '#000',
    width: 145,
    height: 145,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePriceContainer: {
    flexDirection: 'column',
  },
  priceContainer: {
    backgroundColor: '#3E54AC1A',
    marginTop: 8,
    padding: 8,
    borderRadius: 5,
    paddingLeft: 12,
  },
  buttonContainer: {
    // justifyContent: 'center',
    // alignItems: 'center',
    marginLeft: 60,
    marginTop: -15,
    width: '60%',
  },
  button: {
    backgroundColor: '#3E54AC',
    width: 90,
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 28,
  },
  backContainer: {
    flexDirection: 'row',
    marginLeft: 20,
    marginTop: 10,
    alignItems: 'center',
  },
  backButtonText: {
    fontSize: 15,
    color: '#3E54AC',
    fontWeight: '500',
    marginLeft: 18,
  },
  ImageContainer: {
    height: '15%',
    // width: '100%',
    marginTop: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
    // backgroundColor: '#000',
    // marginLeft: 30,
    // justifyContent: 'center',
  },
  image: {
    height: 200,
    width: 200,
    justifyContent: 'center',
    marginTop: 20,
    marginLeft: 25,
    // backgroundColor: '#000',
  },
  Addimage: {
    height: 109,
    width: 252,
    backgroundColor: Colors.white,
    marginTop: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  ImageBox: {
    // marginTop: 40,
    // marginLeft: 55,
    // marginBottom: 120,
    // backgroundColor: '#000',
    // width: '60%',
    // height: '90%',
  },
  Price: {
    width: 255,
    height: 48,
    backgroundColor: Colors.white,
    elevation: 4,
    marginTop: 10,
    borderRadius: 15,
  },
  touchableContainer: {
    height: 40,
    width: 100,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.iconscolor,
    // padding: 20,
  },
  Sizecontainer: {
    marginTop: 20,
    height: '7%',
    width: '30%',
  },
  removeText: {
    color: Colors.white,
    alignItems: 'center',
  },
  Sizetext: {
    // width: '40%',
    // height: '40%',
    // padding: 1,
    fontSize: 18,
    color: Colors.iconscolor,
    fontWeight: '700',
  },
  addImagesText: {
    fontSize: 18,
    color: Colors.iconscolor,
    fontWeight: '700',
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  removeContainer: {
    // padding: 20,
    alignItems: 'center',
  },
  imagehorizontal: {
    // height: -10,
    width: 300,
    // marginTop: -100,
  },
  Pricetext: {
    fontSize: 18,
    color: Colors.iconscolor,
    fontWeight: '700',
    marginTop: 30,
  },
  AddIcon: {
    alignItems: 'center',
    color: Colors.iconscolor,
    fontSize: 20,
    marginTop: 40,
    justifyContent: 'center',
  },
  imagesText: {
    fontSize: 18,
    color: Colors.iconscolor,
    fontWeight: '700',
    // marginTop: 20,
  },
});
export default OwnerEditItemstyles;
