import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const OwnerImagestyles = StyleSheet.create({
  imagehorizontal: {
    height: -10,
    width: 300,
  },
  TitletextContainer: {
    flexDirection: 'row',
    margin: 15,
    marginLeft: 30,
  },
  form: {
    marginLeft: 10,
  },
  touchableContainer: {
    height: 40,
    width: 100,
    marginLeft: 115,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#9747FF',
  },
  removeText: {
    fontWeight: 400,
    color: Colors.white,
    alignItems: 'center',
  },
  removeContainer: {
    alignItems: 'center',
  },
  Icon: {
    color: Colors.iconscolor,
    fontSize: 20,
    marginTop: 23,
  },
  TitleText: {
    fontSize: 18,
    color: Colors.iconscolor,
    fontWeight: '700',
    marginTop: 20,
  },
  ImageContainer: {
    height: '15%',
    marginTop: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  image: {
    height: 200,
    width: 200,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginLeft: 65,
  },
  Addimage: {
    height: 163,
    width: '150%',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ImageBox: {
    marginTop: 20,
    marginLeft: 15,
    width: '60%',
    height: '90%',
  },
  AddIcon: {
    alignItems: 'center',
    color: Colors.iconscolor,
    fontSize: 20,
    marginTop: 40,
    justifyContent: 'center',
  },
  imagesText: {
    fontSize: 20,
    color: 'rgba(255, 255, 255, 0.5)',
    fontWeight: '500',
  },
  Price: {
    fontSize: 16,
    fontWeight: '400',
    color: '#FFFFFF',
    width: '148%',
    marginLeft: 2,
    height: 56,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    elevation: 4,
    marginTop: 11,
    borderRadius: 8,
  },
  quantity: {
    fontSize: 16,
    fontWeight: '400',
    color: '#FFFFFF',
    width: '148%',
    height: 56,
    marginLeft: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    elevation: 4,
    marginTop: 17,
    borderRadius: 8,
  },
  Pricetext: {
    fontSize: 18,
    color: Colors.iconscolor,
    fontWeight: '700',
    marginTop: 30,
  },
  Quantitytext: {
    fontSize: 18,
    color: Colors.iconscolor,
    fontWeight: '700',
    marginTop: 20,
  },
  Scroll: {
    height: 788,
    backgroundColor: Colors.main,
  },
  Sizecontainer: {
    marginTop: 20,
    height: '7%',
    width: '30%',
    marginLeft: 2,
  },
  Sizetext: {
    // width: '40%',
    // height: '40%',
    // padding: 1,
    fontSize: 18,
    color: Colors.iconscolor,
    fontWeight: '700',
  },
  addImagesText: {
    fontSize: 18,
    color: Colors.iconscolor,
    fontWeight: '700',
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  mainTouchable: {
    height: 48,
    width: 250,
    backgroundColor: '#3E54AC',
    marginTop: 30,
    borderRadius: 13,
    color: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    // marginLeft: -30,
  },
});
export default OwnerImagestyles;
