import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
const styles = StyleSheet.create({
  scrollContainer: {
    backgroundColor: Colors.main,
    height: '100%',
    width: '100%',
  },
  mainContainer: {
    backgroundColor: Colors.main,
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  Container: {
    // height: '100%',
    width: '100%',
    // margin: 26,
    // backgroundColor: Colors.white,
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  titleText: {
    // marginTop: 60,
    fontSize: 30,
    fontWeight: '700',
    color: Colors.white,
    // margin: 25,
    // marginLeft: 55,
  },
  textView: {height: 43, width: 286},
  titleTextContainer: {
    marginBottom: 30,
    marginTop: 10,
    // height: 150,
    // justifyContent: 'center',
    // flex: 1,
    flexDirection: 'row',
    // display: 'flex',
    // gap: 80,
    // marginLeft: 15,
    // backgroundColor: 'green',
    width: '90%',
  },
  card: {
    // backgroundColor: 'white',
    height: '67%',
    width: 320,
    // padding: 35,
    borderRadius: 15,
    margin: 15,
    marginLeft: 45,
    alignContent: 'center',
    justifyContent: 'center',
    shadowColor: '#52006A',
    // elevation: 1,
  },
  cardText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: '400',
    marginTop: 10,
    marginLeft: 20,
  },
  cardText1: {
    color: '#3E54AC',
    fontSize: 18,
    fontWeight: '700',
    marginRight: 20,
  },
  textinput: {
    backgroundColor: Colors.Textinput,
    width: '90%',
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 10,
    padding: 10,
    marginLeft: 15,
    // opacity: 0.2,
    borderColor: '#3E54AC',
    color: 'white',
  },
  touchableText: {
    // margin:15,
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
    justifyContent: 'center',
  },
  touchablebtn: {
    height: 59,
    width: 320,
    backgroundColor: '#9747FF',
    marginLeft: 0,
    marginTop: 20,
    borderRadius: 100,
    color: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  touchablebtnContainer: {
    justifyContent: 'center',
    // marginLeft: -20,
    // marginTop: -20,
    // alignItems:"center",
  },
  subTitileText: {
    color: '#FFFFFF',
    fontSize: 20,
  },
  Logintext: {
    marginTop: 10,
    alignItems: 'center',
    marginRight: 20,
    margin: 15,
  },
  sign: {
    color: '#3E54AC',
    fontSize: 14,
    opacity: 3,
  },
  dontText: {
    margin: 25,
    marginTop: 1,
    marginRight: 2,
    marginBottom: 10,
  },
  textfirst: {
    height: 40,
    width: 115,
    backgroundColor: 'white',
    borderRadius: 10,
    // marginBottom: 20,
    // flexDirection: 'row',
  },
  image: {
    width: '100%',
    height: 100,
    marginTop: 20,
    // marginLeft: 50,
    // paddingRight: 30,
  },
  emailText: {
    backgroundColor: 'white',
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 10,
    padding: 10,
    borderColor: '#3E54AC',
  },
  errorTxt: {
    fontSize: 12,
    color: 'red',
    // position: 'absolute',
    // bottom: -18, // Adjust this value to position the error text as desired
    // width: '100%', // Make sure the error text spans the full width of the card container
    // textAlign: 'center', // Center the error text horizontally within the card container
  },
  buttonContainer: {
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  signText: {
    color: '#3E54AC',
    fontSize: 14,
    opacity: 3,
    flexDirection: 'row',
  },
  signuptext: {
    marginTop: 20,
    alignItems: 'center',
    color: Colors.white,
    //marginRight: 20,
    //margin: 15,
    //paddingLeft: 25,
  },
  LoginText: {
    marginTop: 20,
    alignItems: 'center',
    color: '#9747FF',
    marginBottom: 10,
  },
});
export default styles;
